title = "Thintuit Site"
baseURL = "https://data.thintuit.com/"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
# disqusShortname = jinliccs

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10  # 数值越小排序越靠前

[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 30

[[menu.main]]
  name = "Login"       # 新增登录按钮
  url = "/login/"
  weight = 40

[[menu.main]]
  name = "Register"       # 新增登录按钮
  url = "/register/"
  weight = 50

[languages]
  [languages.en]
    title = "Thintuit."
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "TBD"
  favicon = "images/1f913.png"
  site_logo = "images/1f913.png"
  description = "Thintuit."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3


disableKinds = ["taxonomy", "term", "RSS"]

